[package]
name = "tools"
version = "0.1.0"
edition = "2024"

[dependencies]
base64 = "0.22.1"
dotenvy = "0.15.7"
image = "0.25.9"
oxipng = "10.1.0"
reqwest = { version = "0.12.28", features = ["blocking", "json"] }
serde_json = "1.0.140"
tempfile = "3.24.0"
thiserror = "2.0.18"
